worker_processes 1;

events { worker_connections 1024; }

http {
    
    upstream student {
        server student:5000;
    }
    upstream admin {
        server admin:5000;
    }
    upstream driver {
        server driver:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://student;  # トップページを student サービスへ
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /student/ {
            proxy_pass http://student/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /admin/ {
            proxy_pass http://admin/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /driver/ {
            proxy_pass http://driver/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}
