worker_processes 1;

events { worker_connections 1024; }

http {
    upstream student {
        server student:5000;
    }
    upstream admin {
        server admin:5000;
    }
    upstream driver {
        server driver:5000;
    }

    server {
        listen 80;
        root /etc/nginx/html;

        # 共通のメンテナンスページ設定
        error_page 502 503 504 /maintenance.html;
        location = /maintenance.html {
            root /etc/nginx/html;
            internal;
        }

        location / {
            proxy_pass http://student;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 2s;
            proxy_read_timeout 5s;

            proxy_intercept_errors on;
            error_page 502 503 504 = /maintenance.html;
        }


        # 各サービスに対して /health を事前チェック
        location /student {
            rewrite ^/student/?(.*)$ /$1 break;
            proxy_pass http://student;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 2s;
            proxy_read_timeout 5s;

            # /health チェック
            proxy_intercept_errors on;
            error_page 502 503 504 = /maintenance.html;
        }

        location /admin {
            rewrite ^/admin/?(.*)$ /$1 break;
            proxy_pass http://admin;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 2s;
            proxy_read_timeout 5s;

            proxy_intercept_errors on;
            error_page 502 503 504 = /maintenance.html;
        }

        location /driver {
            rewrite ^/driver/?(.*)$ /$1 break;
            proxy_pass http://driver;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 2s;
            proxy_read_timeout 5s;

            proxy_intercept_errors on;
            error_page 502 503 504 = /maintenance.html;
        }
    }
}
